[stringdemoapi.errors]

CannotInvokeOperation = "Operation {{.Service}}:{{.Operation}} could not be invoked. error is {{.Error}}"
SecurityException = "Invalid secure token"
CannotCastResponse = "Error in casting response. Response is {{.Response}}"
UnexpectedProxyInputParameter = "Unexpected parameter. Expected parameter type to be *api.CountRequest"

