// Code generated by "stringer -linecomment -type=WegoErrorCode"; DO NOT EDIT.

package err

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CannotInvokeOperation-200000]
	_ = x[SecurityException-200001]
	_ = x[CannotCastResponse-200002]
}

const _WegoErrorCode_name = "stringdemoservice.errors.CannotInvokeOperationstringdemoservice.errors.SecurityExceptionstringdemoservice.errors.CannotCastResponse"

var _WegoErrorCode_index = [...]uint8{0, 46, 88, 131}

func (i WegoErrorCode) String() string {
	i -= 200000
	if i < 0 || i >= WegoErrorCode(len(_WegoErrorCode_index)-1) {
		return "WegoErrorCode(" + strconv.FormatInt(int64(i+200000), 10) + ")"
	}
	return _WegoErrorCode_name[_WegoErrorCode_index[i]:_WegoErrorCode_index[i+1]]
}
